// This file stores all of the actions types for redux
// For Players:
const NEW_USERNAME = "NEW_USERNAME";
const ADD_PLAYER = "ADD_PLAYER";

// For gameState:
const NEW_GAMEPHASE = "NEW_GAMEPHASE";

// For gameActions:
const PLAYER_ACTION = "PLAYER_ACTION";
const TOGGLE_CARD = "TOGGLE_CARD";
const SELECT_SUB = "SELECT_SUB";
const SELECT_ADD = "SELECT_ADD";
const UPDATE_SELECT_NUM = "UPDATE_SELECT_NUM";

// For roleSelect:
const NUMROLESELECTED = "NUMROLESELECTED"

// REMEMBER TO UPDATED TYPES IN CLIENT FOLDER AS WELL
// Actions that will dispatch from server:
const UPDATE_PLAYERS = "UPDATE_PLAYERS";
const UPDATE_GAMEPHASE = "UPDATE_GAMEPHASE";
const UPDATE_ROLE = "UPDATE_ROLE";
const UPDATE_ROLEDESCRIPTION = "UPDATE_ROLEDESCRIPTION"
const ROLE_TOGGLE = "ROLE_TOGGLE";
const ROLE_ADD = "ROLE_ADD";
const ROLE_SUB = "ROLE_SUB";
const MAJORITY_ADD = "MAJORITY_ADD";
const MAJORITY_SUB = "MAJORITY_SUB";
const MAJORITY_RESET = "MAJORITY_RESET";
const UPDATE_MAJORITY = "UPDATE_MAJORITY";
const UPDATE_MAJORITY_READY = "UPDATE_MAJORITY_READY";
const UPDATE_ALL_ROLES = "UPDATE_ALL_ROLES";
const UPDATE_GAME_ROLES = "UPDATE_GAME_ROLES";
const UPDATE_DAYDESCRIPTION = "UPDATE_DAYDESCRIPTION";

module.exports.types = {
  NEW_USERNAME,
  ADD_PLAYER,

  NEW_GAMEPHASE,

  PLAYER_ACTION,
  TOGGLE_CARD,
  SELECT_SUB,
  SELECT_ADD,
  UPDATE_SELECT_NUM,

  NUMROLESELECTED,

  UPDATE_PLAYERS,
  UPDATE_GAMEPHASE,
  UPDATE_ROLE,
  UPDATE_ROLEDESCRIPTION,
  ROLE_TOGGLE,
  ROLE_ADD,
  ROLE_SUB,
  MAJORITY_ADD,
  MAJORITY_SUB,
  MAJORITY_RESET,
  UPDATE_MAJORITY,
  UPDATE_MAJORITY_READY,
  UPDATE_ALL_ROLES,
  UPDATE_GAME_ROLES,
  UPDATE_DAYDESCRIPTION,
}
